# Generated by Django 6.0.4 on 2026-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
