# Generated by Django 6.0.4 on 2026-05-02 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_record_options_record_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits and contain only numbers.', regex='^\\d{9,15}$')]),
        ),
    ]
